RS1 - seminarski rad/Models/ErrorViewModel.cs
using System;

namespace RS1___seminarski_rad.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RS1 - seminarski rad/ViewModels/AutentifikacijaPrijavaVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RS1.ViewModels
{
    public class AutentifikacijaPrijavaVM
    {
        public string KorisnickoIme { get; set; }
        public string Lozinka { get; set; }
        public int KorisnikID { get; set; }
    }
}

RS1 - seminarski rad/ViewModels/KorisnikEvidentirajVM.cs
using Data.EFModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RS_SEMINARSKI.ModelViews
{
    public class KorisnikEvidentirajVM
    {
        public int KorisnikID { get; set; }
        public string ImeKorisnika { get; set; }
        public string PrezimeKorisnika { get; set; }
        public string KorisnickoIme { get; set; }
        public string Lozinka { get; set; }
        public string Email { get; set; }
        public string BrojTelefona { get; set; }
        public string AdresaStanovanja { get; set; }
    }
}

RS1 - seminarski rad/Controllers/AutentifikacijaController.cs
using Data.EF;
using Microsoft.AspNetCore.Mvc;
using RS_SEMINARSKI.Helper;
using RS_SEMINARSKI.ModelViews;
using RS1.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace RS_SEMINARSKI.Controllers
{
    public class AutentifikacijaController : Controller
    {


        public IActionResult Prijava()
        {

            return View("Prijava");
        }
        

        public IActionResult Snimi(AutentifikacijaPrijavaVM m)
        {
            MyDBContext db = new MyDBContext();

            var korisnik = db.Korisnici.Where(a => a.Lozinka == m.Lozinka && a.KorisnickoIme == m.KorisnickoIme).SingleOrDefault(); 

            if(korisnik == null)
            {
                TempData["Poruka"] = "Nisu ispravni podaci za prijavu !"; 
                return Redirect("Prijava");
            }
          
            Get_Set.SetLogiraniKorisnik(HttpContext, korisnik);
            m.KorisnikID = korisnik.KorisnikID;

            KorisnikEvidentirajVM k = new KorisnikEvidentirajVM()
            {
                KorisnickoIme = korisnik.KorisnickoIme,
                Lozinka = korisnik.Lozinka,
                ImeKorisnika = korisnik.ImeKorisnika,
                PrezimeKorisnika = korisnik.PrezimeKorisnika,
                BrojTelefona = korisnik.BrojTelefona,
                AdresaStanovanja = korisnik.AdresaStanovanja,
                Email = korisnik.Email,
                KorisnikID = korisnik.KorisnikID
              
            };


            return Redirect("/Vjencanje/PrikazPocetne?KorisnikID=" + k.KorisnikID);
            //View("~/Views/Vjencanje/PrikazPocetne.cshtml");  jer smo slale model a nismo ga kako terba primile
        }

        public IActionResult Poruka()
        {
            return View("Poruka");
        }

        public IActionResult LogOut()
        {
            Get_Set.SetLogiraniKorisnik(HttpContext, null);
            return Redirect("/"); 
        }
    }
}

RS1 - seminarski rad/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RS1___seminarski_rad.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RS1___seminarski_rad.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RS1 - seminarski rad/Views/Autentifikacija/Login.cshtml
@using RS1.ViewModels;
@model AutentifikacijaPrijavaVM
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

@{ var poruka = TempData["Message"]; }

@{
    Layout = null;
}

<style>

    /*.background {
        background-image: url("https://economictimes.indiatimes.com/thumb/msid-60334367,width-1200,height-900,resizemode-4,imgsize-56987/tdmc/your-money/these-are-the-participants-in-your-insurance-contract.jpg?from=mdr");
        background-position: center;
        background-size: cover;
    }

        .loginView {
        background-color: white;
        height: 500px;
        width: 100%;
        top: 20px;
        bottom: 20px;
        border-radius: 10px;
    }


    #Error {
        font-size: 30px;
        color: crimson;
        margin-top: 200px;
        margin-left: 600px;
        font-weight: bold;
    }*/

    body {
        margin: 0;
        color: #6a6f8c;
        background: #c8c8c8;
        font: 600 16px/18px 'Open Sans', sans-serif;
        background: url(https://m.economictimes.com/thumb/msid-60334367,width-1200,height-900,resizemode-4,imgsize-56987/tdmc/your-money/these-are-the-participants-in-your-insurance-contract.jpg);
        background-repeat: no-repeat;
        background-size: 100% 100%;
    }

    .login-box {
        width: 100%;
        margin: auto;
        max-width: 100%;
        min-height: 100%;
        position: relative;
        background-color: white;
        box-shadow: 0 12px 15px 0 rgba(0, 0, 0, .24), 0 17px 50px 0 rgba(0, 0, 0, .19)
    }

    .login-snip {
        width: 100%;
        height: 100%;
        position: absolute;
        padding: 90px 70px 50px 70px;
        background: rgba(0, 77, 77, .9)
    }

        .login-snip .login,
        .login-snip .sign-up-form {
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            position: absolute;
            transform: rotateY(180deg);
            backface-visibility: hidden;
            transition: all .4s linear
        }

        .login-snip .sign-in,
        .login-snip .sign-up,
        .login-space .group .check {
            display: none
        }

        .login-snip .tab,
        .login-space .group .label,
        .login-space .group .button {
            text-transform: uppercase
        }

        .login-snip .tab {
            font-size: 22px;
            margin-right: 15px;
            padding-bottom: 5px;
            margin: 0 15px 10px 0;
            display: inline-block;
            border-bottom: 2px solid transparent
        }

        .login-snip .sign-in:checked + .tab,
        .login-snip .sign-up:checked + .tab {
            color: #fff;
            border-color: #1161ee
        }

    .login-space {
        min-height: 345px;
        position: relative;
        perspective: 1000px;
        transform-style: preserve-3d
    }

        .login-space .group {
            margin-bottom: 15px
        }

            .login-space .group .label,
            .login-space .group .input,
            .login-space .group .button {
                width: 100%;
                color: #fff;
                display: block
            }

            .login-space .group .input,
            .login-space .group .button {
                border: none;
                padding: 15px 20px;
                border-radius: 25px;
                background: rgba(255, 255, 255, .1)
            }

            .login-space .group input[data-type="password"] {
                text-security: circle;
                -webkit-text-security: circle
            }

            .login-space .group .label {
                color: #aaa;
                font-size: 12px
            }

            .login-space .group .button {
                background: #1161ee
            }

            .login-space .group label .icon {
                width: 15px;
                height: 15px;
                border-radius: 2px;
                position: relative;
                display: inline-block;
                background: rgba(255, 255, 255, .1)
            }

                .login-space .group label .icon:before,
                .login-space .group label .icon:after {
                    content: '';
                    width: 10px;
                    height: 2px;
                    background: #fff;
                    position: absolute;
                    transition: all .2s ease-in-out 0s
                }

                .login-space .group label .icon:before {
                    left: 3px;
                    width: 5px;
                    bottom: 6px;
                    transform: scale(0) rotate(0)
                }

                .login-space .group label .icon:after {
                    top: 6px;
                    right: 0;
                    transform: scale(0) rotate(0)
                }

            .login-space .group .check:checked + label {
                color: #fff
            }

                .login-space .group .check:checked + label .icon {
                    background: #1161ee
                }

                    .login-space .group .check:checked + label .icon:before {
                        transform: scale(1) rotate(45deg)
                    }

                    .login-space .group .check:checked + label .icon:after {
                        transform: scale(1) rotate(-45deg)
                    }

    .login-snip .sign-in:checked + .tab + .sign-up + .tab + .login-space .login {
        transform: rotate(0)
    }

    .login-snip .sign-up:checked + .tab + .login-space .sign-up-form {
        transform: rotate(0)
    }

    *,
    :after,
    :before {
        box-sizing: border-box
    }

    .clearfix:after,
    .clearfix:before {
        content: '';
        display: table
    }

    .clearfix:after {
        clear: both;
        display: block
    }

    a {
        color: inherit;
        text-decoration: none
    }

    .hr {
        height: 2px;
        margin: 60px 0 50px 0;
        background: rgba(255, 255, 255, .2)
    }

    .foot {
        text-align: center
    }

    .card {
        width: 500px;
        left: 100px
    }

    ::placeholder {
        color: #b3b3b3
    }
</style>



<!DOCTYPE html>
<html>

<head>
</head>

<body>

    <form asp-controller="Autentifikacija" asp-action="Snimi">

        <div class="row">
            <div class="col-md-6 mx-auto p-0">
                <div class="card">
                    <div class="login-box">
                        <div class="login-snip">
                            <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Login</label> <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Sign Up</label>
                            <div class="login-space">
                                <div class="login">
                                    <div class="group"> <label for="user" class="label">Username</label> <input id="user" type="text" class="input" placeholder="Enter your username" asp-for="KorisnickoIme"> </div>
                                    <div class="group"> <label for="pass" class="label">Password</label> <input id="pass" type="password" class="input" data-type="password" placeholder="Enter your password" asp-for="Lozinka"> </div>
                                    <div class="group"> <input id="check" type="checkbox" class="check" checked> <label for="check"><span class="icon"></span> Keep me Signed in</label> </div>
                                    <div class="group"> <input type="submit" class="button" value="Sign In"> </div>
                                    <div class="hr"></div>
                                    <div class="foot"> <a href="#">Forgot Password?</a> </div>
                                </div>
                                <div class="sign-up-form">
                                    <div class="group"> <label for="user" class="label">Username</label> <input id="user" type="text" class="input" placeholder="Create your Username"> </div>
                                    <div class="group"> <label for="pass" class="label">Password</label> <input id="pass" type="password" class="input" data-type="password" placeholder="Create your password"> </div>
                                    <div class="group"> <label for="pass" class="label">Repeat Password</label> <input id="pass" type="password" class="input" data-type="password" placeholder="Repeat your password"> </div>
                                    <div class="group"> <label for="pass" class="label">Email Address</label> <input id="pass" type="text" class="input" placeholder="Enter your email address"> </div>
                                    <div class="group"> <input type="submit" class="button" value="Sign Up"> </div>
                                    <div class="hr"></div>
                                    <div class="foot"> <label for="tab-1">Already Member?</label> </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

</form>
</body>
</html>

RS1 - seminarski rad/Views/Autentifikacija/Message.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Uspjesno ste se registrovali! :)

RS1 - seminarski rad/Views/Autentifikacija/Poruka.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Uspjesno ste se registrovali! :)

RS1 - seminarski rad/Views/Autentifikacija/Prijava.cshtml
@using RS1.ViewModels;
@model AutentifikacijaPrijavaVM
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

@{ var poruka = TempData["Poruka"]; }

@{
    Layout = null;
}

<style>

    /*.background {
        background-image: url("https://economictimes.indiatimes.com/thumb/msid-60334367,width-1200,height-900,resizemode-4,imgsize-56987/tdmc/your-money/these-are-the-participants-in-your-insurance-contract.jpg?from=mdr");
        background-position: center;
        background-size: cover;
    }

        .loginView {
        background-color: white;
        height: 500px;
        width: 100%;
        top: 20px;
        bottom: 20px;
        border-radius: 10px;
    }


    #Error {
        font-size: 30px;
        color: crimson;
        margin-top: 200px;
        margin-left: 600px;
        font-weight: bold;
    }*/

    body {
        margin: 0;
        color: #6a6f8c;
        background: #c8c8c8;
        font: 600 16px/18px 'Open Sans', sans-serif;
        background: url(https://m.economictimes.com/thumb/msid-60334367,width-1200,height-900,resizemode-4,imgsize-56987/tdmc/your-money/these-are-the-participants-in-your-insurance-contract.jpg);
        background-repeat: no-repeat;
        background-size: 100% 100%;
    }

    .login-box {
        width: 100%;
        margin: auto;
        max-width: 525px;
        min-height: 670px;
        position: relative;
        background-color: white;
        box-shadow: 0 12px 15px 0 rgba(0, 0, 0, .24), 0 17px 50px 0 rgba(0, 0, 0, .19)
    }

    .login-snip {
        width: 100%;
        height: 100%;
        position: absolute;
        padding: 90px 70px 50px 70px;
        background: rgba(0, 77, 77, .9)
    }

        .login-snip .login,
        .login-snip .sign-up-form {
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            position: absolute;
            transform: rotateY(180deg);
            backface-visibility: hidden;
            transition: all .4s linear
        }

        .login-snip .sign-in,
        .login-snip .sign-up,
        .login-space .group .check {
            display: none
        }

        .login-snip .tab,
        .login-space .group .label,
        .login-space .group .button {
            text-transform: uppercase
        }

        .login-snip .tab {
            font-size: 22px;
            margin-right: 15px;
            padding-bottom: 5px;
            margin: 0 15px 10px 0;
            display: inline-block;
            border-bottom: 2px solid transparent
        }

        .login-snip .sign-in:checked + .tab,
        .login-snip .sign-up:checked + .tab {
            color: #fff;
            border-color: #1161ee
        }

    .login-space {
        min-height: 345px;
        position: relative;
        perspective: 1000px;
        transform-style: preserve-3d
    }

        .login-space .group {
            margin-bottom: 15px
        }

            .login-space .group .label,
            .login-space .group .input,
            .login-space .group .button {
                width: 100%;
                color: #fff;
                display: block
            }

            .login-space .group .input,
            .login-space .group .button {
                border: none;
                padding: 15px 20px;
                border-radius: 25px;
                background: rgba(255, 255, 255, .1)
            }

            .login-space .group input[data-type="password"] {
                text-security: circle;
                -webkit-text-security: circle
            }

            .login-space .group .label {
                color: #aaa;
                font-size: 12px
            }

            .login-space .group .button {
                background: #1161ee
            }

            .login-space .group label .icon {
                width: 15px;
                height: 15px;
                border-radius: 2px;
                position: relative;
                display: inline-block;
                background: rgba(255, 255, 255, .1)
            }

                .login-space .group label .icon:before,
                .login-space .group label .icon:after {
                    content: '';
                    width: 10px;
                    height: 2px;
                    background: #fff;
                    position: absolute;
                    transition: all .2s ease-in-out 0s
                }

                .login-space .group label .icon:before {
                    left: 3px;
                    width: 5px;
                    bottom: 6px;
                    transform: scale(0) rotate(0)
                }

                .login-space .group label .icon:after {
                    top: 6px;
                    right: 0;
                    transform: scale(0) rotate(0)
                }

            .login-space .group .check:checked + label {
                color: #fff
            }

                .login-space .group .check:checked + label .icon {
                    background: #1161ee
                }

                    .login-space .group .check:checked + label .icon:before {
                        transform: scale(1) rotate(45deg)
                    }

                    .login-space .group .check:checked + label .icon:after {
                        transform: scale(1) rotate(-45deg)
                    }

    .login-snip .sign-in:checked + .tab + .sign-up + .tab + .login-space .login {
        transform: rotate(0)
    }

    .login-snip .sign-up:checked + .tab + .login-space .sign-up-form {
        transform: rotate(0)
    }

    *,
    :after,
    :before {
        box-sizing: border-box
    }

    .clearfix:after,
    .clearfix:before {
        content: '';
        display: table
    }

    .clearfix:after {
        clear: both;
        display: block
    }

    a {
        color: inherit;
        text-decoration: none
    }

    .hr {
        height: 2px;
        margin: 60px 0 50px 0;
        background: rgba(255, 255, 255, .2)
    }

    .foot {
        text-align: center
    }

    .card {
        width: 500px;
        left: 100px
    }

    ::placeholder {
        color: #b3b3b3
    }
</style>



<!DOCTYPE html>
<html>

<head>
</head>

<body>

    <form asp-controller="Autentifikacija" asp-action="Snimi">

        @*<div class="container w-50">
                <h1 class="text-center">Prijava</h1>
                <div>
                    <input type="text" class="form-control" placeholder="Korisnicko ime" aria-label="KorisnickoIme" aria-describedby="basic-addon1" asp-for="KorisnickoIme">
                </div>

                <div>
                    <input type="password" class="form-control" placeholder="Korisnicko ime" aria-label="KorisnickoIme" aria-describedby="basic-addon1" asp-for="Lozinka">
                </div>

                <button class="btn btn-primary" type="submit">Prijava</button>

                <div id="Error">@poruka</div>
            </div>*@

        <div class="row">
            <div class="col-md-6 mx-auto p-0">
                <div class="card">
                    <div class="login-box">
                        <div class="login-snip">
                            <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Login</label> <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Sign Up</label>
                            <div class="login-space">
                                <div class="login">
                                    <div class="group"> <label for="user" class="label">Username</label> <input id="user" type="text" class="input" placeholder="Enter your username" asp-for="KorisnickoIme"> </div>
                                    <div class="group"> <label for="pass" class="label">Password</label> <input id="pass" type="password" class="input" data-type="password" placeholder="Enter your password" asp-for="Lozinka"> </div>
                                    <div class="group"> <input id="check" type="checkbox" class="check" checked> <label for="check"><span class="icon"></span> Keep me Signed in</label> </div>
                                    <div class="group"> <input type="submit" class="button" value="Sign In"> </div>
                                    <div class="hr"></div>
                                    <div class="foot"> <a href="#">Forgot Password?</a> </div>
                                </div>
                                <div class="sign-up-form">
                                    <div class="group"> <label for="user" class="label">Username</label> <input id="user" type="text" class="input" placeholder="Create your Username"> </div>
                                    <div class="group"> <label for="pass" class="label">Password</label> <input id="pass" type="password" class="input" data-type="password" placeholder="Create your password"> </div>
                                    <div class="group"> <label for="pass" class="label">Repeat Password</label> <input id="pass" type="password" class="input" data-type="password" placeholder="Repeat your password"> </div>
                                    <div class="group"> <label for="pass" class="label">Email Address</label> <input id="pass" type="text" class="input" placeholder="Enter your email address"> </div>
                                    <div class="group"> <input type="submit" class="button" value="Sign Up"> </div>
                                    <div class="hr"></div>
                                    <div class="foot"> <label for="tab-1">Already Member?</label> </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

</form>
</body>
</html>

RS1 - seminarski rad/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RS1___seminarski_rad</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RS1___seminarski_rad</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - RS1___seminarski_rad - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>